version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: imen1amami/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "your_root_password",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect"
      }'
    stdin_open: true
    tty: true

  mysql-exporter:
    image: prom/mysqld-exporter
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=root:your_root_password@tcp(mysqldb:3306)/db  # MySQL connection string
    ports:
      - "9104:9104"  # Exporter port

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Path to the Prometheus config file
    ports:
      - "9090:9090"  # Prometheus UI port

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Grafana UI port
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set Grafana admin password

volumes:
  db:
  prometheus_data: