version: "3.8"
services :
  mysqldb:
    image: mysql:latest
    restart : unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-achats:
    depends_on:
      - mysqldb
    image: torkhaniroua/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON : '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
      "spring.datasource.username":"root",
      "spring.datasource.password": "root",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty : true
volumes:
  db:
networks:
  custom_network:
    driver: bridge