services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes  # Allow empty password
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-timesheet:
    depends_on:
      - mysqldb
    image: imen1amami/tp-foyer:5.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "",  # No password set
        "spring.jpa.show-sql": true,
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

  mysql-exporter:
    image: prom/mysqld-exporter
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=root:@tcp(mysqldb:3306)/  # No password set
    ports:
      - "9104:9104"  # Expose MySQL exporter on port 9104

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount your Prometheus config
    ports:
      - "9090:9090"  # Expose Prometheus on port 9090

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose Grafana on port 3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Grafana admin username
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana admin password

volumes:
  db: