global:
  scrape_interval: 15s  
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']  

  - job_name: 'app-timesheet'
    static_configs:
      - targets: ['app-timesheet:8089']  