global:
  scrape_interval: 15s  
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'  
      - targets: ['192.168.50.2:9100'] 

  - job_name: 'app-timesheet'
    static_configs:
      - targets: ['app-timesheet:8089']