global:
  scrape_interval: 15s  # Scrape every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds

scrape_configs:

 - job_name: 'app-timesheet'
    static_configs:
      - targets: ['app-timesheet:8089']  